### ISSUE TITLE
Error on synchronize

### ISSUE THREAD

**Issue by peter-lawrey** [HubPress/hubpress.io#537]
I have updated to 0.9.1

After posting an article, the "Posts" page reported 0 posts. On clicking refresh I get

app.3e89e3d9c935e845e2fd.js:1 Uncaught (in promise) TypeError: t.replace is not a function
    at h (https://vanilla-java.github.io/_nuxt/app.3e89e3d9c935e845e2fd.js:1:143861)
    at https://vanilla-java.github.io/_nuxt/app.3e89e3d9c935e845e2fd.js:1:142090
    at Array.map (<anonymous>)
    at https://vanilla-java.github.io/_nuxt/app.3e89e3d9c935e845e2fd.js:1:142059
    at l (https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:211437)
    at S._settlePromiseFromHandler (https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:184806)
    at S._settlePromise (https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:185606)
    at S._settlePromiseCtx (https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:186112)
    at https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:141269
From previous event:
    at S.P [as _captureStackTrace] (https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:154695)
    at S._then (https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:180263)
    at S.then (https://vanilla-java.github.io/_nuxt/vendor.099e66f2e693b444d03c.js:2:178619)
    at Object.a [as synchronize] (https://vanilla-java.github.io/_nuxt/app.3e89e3d9c935e845e2fd.js:1:121409)
    at https://vanilla-java.github.io/_nuxt/app.3e89e3d9c935e845e2fd.js:1:33343

**Comment by peter-lawrey** [comment]
So now I can't remove the test post.

**Comment by anthonny** [comment]
If you refresh the page, and sync again, does the problem persist?
